#!/usr/bin/env python3
"""Generates assets/globe.js: evenly spaced dots on land, for the dot globe.

    pip install global-land-mask
    python3 tools/make_globe.py

Rows every STEP degrees of latitude; within a row the dots keep the same
ground spacing (longitude step widens by 1/cos(lat)). Antarctica is skipped.
"""
import math
import pathlib

from global_land_mask import globe

STEP = 1.7
pts = []
lat = -58.0
while lat <= 82:
    n = max(1, int(round(360 * math.cos(math.radians(lat)) / STEP)))
    off = (lat * 7.31) % 1.0  # rows slightly offset so columns do not line up
    for i in range(n):
        lon = -180 + (i + off) * 360 / n
        if globe.is_land(lat, lon):
            pts.append((round(lat, 2), round(lon, 2)))
    lat += STEP

out = pathlib.Path(__file__).resolve().parent.parent / 'assets' / 'globe.js'
flat = ','.join(f'{a},{b}' for a, b in pts)
out.write_text('// Generated by tools/make_globe.py: [lat, lon, lat, lon, ...] land dots\n'
               f'const GLOBE_DOTS = new Float32Array([{flat}]);\n')
print(f'{len(pts)} dots → {out} ({out.stat().st_size // 1024} KB)')
